# env:
# - name: CNB_APP_DIR
#   value: /workspace
# - name: CNB_ANALYZED_PATH
#   value: /layers/analyzed.toml
# - name: CNB_BUILDPACKS_DIR
#   value: /cnb/buildpacks
# - name: CNB_CACHE_IMAGE
#   value: asia.gcr.io/revanth-madasu913/app-engine-tmp/build-cache/ttl-7d/default/buildpack-cache:8cc7e067-5815-46de-bc3c-514b25a2ba6a
# - name: CNB_GROUP_PATH
#   value: /layers/group.toml
# - name: CNB_LAYERS_DIR
#   value: /layers
# - name: CNB_LOG_LEVEL
#   value: debug
# - name: CNB_PLAN_PATH
#   value: /layers/plan.toml
# - name: CNB_PLATFORM_DIR
#   value: /platform
# - name: CNB_RUN_IMAGE
#   value: asia.gcr.io/gae-runtimes/buildpacks/nodejs12/run:nodejs12_20201129_12_20_0_RC00
# - name: CNB_ANALYZE_SKIP_LAYERS
#   value: false
# - name: GOOGLE_LABEL_BUILDER_VERSION
#   value: nodejs12_20201129_12_20_0_RC00
steps:
- name: 'gcr.io/cloud-builders/gcs-fetcher'
  args: ['--type=Manifest', '--location=gs://staging.revanth-madasu913.appspot.com/ae/9e7e926a-6d6a-485b-b382-b20f0f232f5e/manifest.json', '--dest_dir=/workspace']
- name: 'gcr.io/cloud-builders/gcloud'
  # env:
  # - name: CNB_USER_ID
  #   value: 33
  # - name: CNB_GROUP_ID
  #   value: 33
  # # - name: GAE_YAML_MAIN
  # #   value: 
  # # - name: GOOGLE_ENTRYPOINT
  # #   value: 
  # - name: GAE_APP_ENGINE_APIS
  #   value: false
  args: ['/bin/bash -c chown -R 33:33 /layers && chown -R 33:33 /workspace && chown -R 33:33 $HOME && chown -R 33:33 $BUILDER_OUTPUT && chmod -R 755 /workspace && chmod -R 755 $BUILDER_OUTPUT && mkdir -p "$CNB_PLATFORM_DIR/env" && if [[ -n "" ]]; then echo -n "" > "$CNB_PLATFORM_DIR/env/GAE_YAML_MAIN"; fi && if [[ -n "" ]]; then echo -n "" > "$CNB_PLATFORM_DIR/env/GOOGLE_ENTRYPOINT"; fi && if [[ -n "$GOOGLE_LABEL_BUILDER_VERSION" ]]; then echo -n "$GOOGLE_LABEL_BUILDER_VERSION" > "$CNB_PLATFORM_DIR/env/GOOGLE_LABEL_BUILDER_VERSION"; fi && echo -n "nodejs12" > "$CNB_PLATFORM_DIR/env/GOOGLE_RUNTIME" && echo -n "true" > "$CNB_PLATFORM_DIR/env/GOOGLE_DEBUG" && echo -n "$BUILDER_OUTPUT" > "$CNB_PLATFORM_DIR/env/BUILDER_OUTPUT" && if [[ -n "false" ]]; then echo -n "false" > "$CNB_PLATFORM_DIR/env/GAE_APP_ENGINE_APIS"; fi']
- name: 'gcr.io/gae-runtimes/crane:shell'
  args: ['/busybox/sh -c (crane copy asia.gcr.io/revanth-madasu913/app-engine-tmp/build-cache/ttl-7d/default/buildpack-cache:latest asia.gcr.io/revanth-madasu913/app-engine-tmp/build-cache/ttl-7d/default/buildpack-cache:95d68490-ba5f-4d3e-9056-9e5368dd38a4 || echo "Unable to tag previous cache image. This is expected for new or infrequent deployments.") && (crane copy asia.gcr.io/revanth-madasu913/app-engine-tmp/app/ttl-2h/default/buildpack-app:latest asia.gcr.io/revanth-madasu913/app-engine-tmp/app/ttl-2h:9e7e926a-6d6a-485b-b382-b20f0f232f5e || echo "Unable to tag previous application image. This is expected for new or infrequent deployments.")']
- name: 'asia.gcr.io/gae-runtimes/buildpacks/nodejs12/builder:nodejs12_20201129_12_20_0_RC00'
  args: ['/cnb/lifecycle/detector']
- name: 'asia.gcr.io/gae-runtimes/buildpacks/nodejs12/builder:nodejs12_20201129_12_20_0_RC00'
  # directory: '/layers'
  args: ['/cnb/lifecycle/analyzer asia.gcr.io/revanth-madasu913/app-engine-tmp/app/ttl-2h:9e7e926a-6d6a-485b-b382-b20f0f232f5e']
- name: 'asia.gcr.io/gae-runtimes/buildpacks/nodejs12/builder:nodejs12_20201129_12_20_0_RC00'
  # directory: '/layers'
  args: ['/cnb/lifecycle/restorer']
- name: 'asia.gcr.io/gae-runtimes/buildpacks/nodejs12/builder:nodejs12_20201129_12_20_0_RC00'
  # directory: '/layers'
  args: ['/cnb/lifecycle/builder']
- name: 'asia.gcr.io/gae-runtimes/buildpacks/nodejs12/builder:nodejs12_20201129_12_20_0_RC00'
  # env:
  # - name: CNB_CACHE_IMAGE
  #   value: asia.gcr.io/revanth-madasu913/app-engine-tmp/build-cache/ttl-7d/default/buildpack-cache:latest 
  # # directory: '/layers'
  args: ['/cnb/lifecycle/exporter asia.gcr.io/revanth-madasu913/app-engine-tmp/app/ttl-2h:9e7e926a-6d6a-485b-b382-b20f0f232f5e']
- name: 'gcr.io/gae-runtimes/crane:current'
  args: ['copy asia.gcr.io/revanth-madasu913/app-engine-tmp/app/ttl-2h:9e7e926a-6d6a-485b-b382-b20f0f232f5e asia.gcr.io/revanth-madasu913/app-engine-tmp/app/ttl-2h/default/buildpack-app:latest']